/*
 * Generates, from one source TTF, both halves of the WYSIWYG contract:
 *
 *   1. firmware/src/fonts/lv_font_hs_<weight>_<size>.c — the LVGL fonts the panel
 *      actually renders with.
 *   2. frontend/src/lib/font_metrics.json — the per-glyph advance table the design
 *      editor measures and positions text with.
 *
 * Both come from the same lv_font_conv invocation, so the editor cannot drift from the
 * device by construction. That is the whole point of this file: the previous rasterizer
 * used a fixed 8px bitmap cell while the browser used the system sans-serif at arbitrary
 * px, and the two could never agree on where a string ended.
 *
 * Why the advances are integers
 * -----------------------------
 * lv_font_conv stores adv_w in 1/16 px (lib/writers/lvgl/lv_table_glyf.js:85,
 * `Math.round(advanceWidth * 16)`), and LVGL rounds that to a whole pixel per glyph
 * before advancing the pen (src/font/fmt_txt/lv_font_fmt_txt.c:251,
 * `adv_w = (adv_w + (1 << 3)) >> 4`). So on-device text layout is a sum of INTEGER
 * advances with no sub-pixel accumulation. We precompute exactly that integer here.
 *
 * A browser laying out the same string with the same TTF would use fractional advances
 * and drift by a pixel or two across a long run, which is why the frontend positions
 * glyphs from this table rather than letting CSS lay out a text run.
 *
 * Kerning is deliberately off (--no-kerning here, `font-kerning: none` in the frontend).
 * Kerning is the main source of disagreement between two text engines; without it a
 * string's width is exactly the sum of its glyph advances, which is trivially
 * reproducible on both sides.
 *
 * Run with: npm run generate   (from tools/fonts/)
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const FIRMWARE_FONT_DIR = join(REPO, "firmware", "src", "fonts");
const METRICS_OUT = join(REPO, "frontend", "src", "lib", "font_metrics.json");

/* The size ladder. The design editor's font-size control is restricted to exactly these
 * values (frontend/src/lib/layout.js FONT_SIZES) — an authored size that has no generated
 * font could not be rendered faithfully on the device, so the editor must not offer one.
 *
 * Kept deliberately short: every entry costs flash on a 788KB part. Sizes are spaced so
 * adjacent steps are visibly different rather than evenly spaced. */
const SIZES = [12, 16, 20, 24, 32, 48];

const WEIGHTS = {
  regular: "Montserrat-Regular.ttf",
  semibold: "Montserrat-SemiBold.ttf", /* the design editor's `bold` flag */
};

/* ASCII printable plus the whole Latin-1 supplement. The wire format encodes text as
 * Latin-1 with one byte per glyph (gateway/gateway/protocol.py), so covering 0xA0-0xFF
 * makes every byte the protocol can carry renderable — retiring the old placeholder-box
 * fallback and the hand-authored one-off glyphs for °/Å/Ä/Ö in font_basic.h. */
const RANGES = "0x20-0x7E,0xA0-0xFF";

const BPP = 1; /* the panel is 1-bit; see README — 4bpp would be thresholded away anyway */

function run(args) {
  return execFileSync("npx", ["lv_font_conv", ...args], {
    cwd: HERE,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

/** Reproduce LVGL's per-glyph advance exactly: quantize to 1/16 px the way the writer
 *  does, then round to a whole pixel the way lv_font_fmt_txt.c does. */
function lvglAdvancePx(advanceWidth) {
  const sixteenths = Math.round(advanceWidth * 16);
  return (sixteenths + (1 << 3)) >> 4;
}

mkdirSync(FIRMWARE_FONT_DIR, { recursive: true });

const metrics = {
  _comment:
    "GENERATED by tools/fonts/generate.mjs -- do not edit. Advances are whole pixels, " +
    "matching LVGL's per-glyph rounding on the device. Sum them to lay out a string; " +
    "kerning is disabled on both sides.",
  source: "Montserrat (SIL Open Font License 1.1)",
  bpp: BPP,
  sizes: SIZES,
  weights: Object.keys(WEIGHTS),
  fonts: {},
};

let totalCBytes = 0;

for (const [weight, ttf] of Object.entries(WEIGHTS)) {
  for (const size of SIZES) {
    const name = `lv_font_hs_${weight}_${size}`;
    const cPath = join(FIRMWARE_FONT_DIR, `${name}.c`);
    const fontPath = join(HERE, "src", ttf);

    // 1. The artifact the firmware compiles and renders with.
    run([
      "--font", fontPath,
      "--size", String(size),
      "--bpp", String(BPP),
      "--no-kerning",
      "-r", RANGES,
      "--format", "lvgl",
      "--lv-font-name", name,
      /* Default is "lvgl/lvgl.h", which does not resolve under Zephyr: the LVGL module
       * puts the module root on the include path, so the header is plain <lvgl.h> (the
       * same spelling every other file here uses). */
      "--lv-include", "lvgl.h",
      "-o", cPath,
    ]);

    // 2. The same conversion, dumped as JSON, for the advance table. Same binary, same
    //    flags, same glyph set -- so the numbers cannot disagree with (1).
    const dumpDir = mkdtempSync(join(tmpdir(), "lvfont-"));
    try {
      run([
        "--font", fontPath,
        "--size", String(size),
        "--bpp", String(BPP),
        "--no-kerning",
        "-r", RANGES,
        "--format", "dump",
        "-o", dumpDir,
      ]);
      const info = JSON.parse(readFileSync(join(dumpDir, "font_info.json"), "utf8"));
      const advance = {};
      for (const g of info.glyphs) advance[g.code] = lvglAdvancePx(g.advanceWidth);

      /* Take the vertical metrics from the generated C rather than deriving them from
       * font_info.json's ascent/descent. Those two are raw FreeType values (descent is
       * negative, and both shift with the glyph set), whereas line_height/base_line are
       * what LVGL actually lays a line out with — the same rule as the advances above:
       * read the number the device uses, don't recompute it. */
      const cSource = readFileSync(cPath, "utf8");
      const readField = (field) => {
        const m = cSource.match(new RegExp(`\\.${field}\\s*=\\s*(-?\\d+)`));
        if (!m) throw new Error(`${name}.c: could not find .${field}`);
        return Number(m[1]);
      };

      metrics.fonts[`${weight}-${size}`] = {
        weight,
        size,
        /* Total vertical space one line occupies. */
        lineHeight: readField("line_height"),
        /* Baseline measured from the BOTTOM of the line, LVGL's convention. The glyph
         * baseline sits at (top + lineHeight - baseLine). */
        baseLine: readField("base_line"),
        underlinePosition: readField("underline_position"),
        underlineThickness: readField("underline_thickness"),
        advance,
      };
    } finally {
      rmSync(dumpDir, { recursive: true, force: true });
    }

    const bytes = readFileSync(cPath).length;
    totalCBytes += bytes;
    console.log(`  ${name.padEnd(28)} ${(bytes / 1024).toFixed(1).padStart(7)} KB (C source)`);
  }
}

writeFileSync(METRICS_OUT, JSON.stringify(metrics, null, 2) + "\n");

console.log(`\n${Object.keys(metrics.fonts).length} fonts -> ${FIRMWARE_FONT_DIR}`);
console.log(`metrics -> ${METRICS_OUT}`);
console.log(`total C source: ${(totalCBytes / 1024).toFixed(1)} KB (flash cost is lower --`);
console.log(`  C source includes comments and formatting; check the real cost in the build's`);
console.log(`  FLASH figure, and trim SIZES/WEIGHTS above if it does not fit.)`);
