/*
 * The font ladder shared by the firmware, the gateway wire format, and the design editor.
 *
 * Every font here is generated by tools/fonts/generate.mjs from one source TTF, together
 * with frontend/src/lib/font_metrics.json. The editor lays text out using that metrics
 * table; the panel renders it with these fonts. Same source, same glyph advances, so the
 * preview matches the panel rather than approximating it.
 *
 * The wire format carries a font_id index into hs_font_ladder[] (docs/protocol.md), NOT
 * a pixel size — a size the device has no generated font for could not be rendered
 * faithfully, so the set of legal sizes is closed and shared. HS_FONT_SIZES below must
 * stay in step with SIZES in tools/fonts/generate.mjs and FONT_SIZES in
 * frontend/src/lib/layout.js.
 */

#ifndef HS_FONTS_H_
#define HS_FONTS_H_

#include <stdbool.h>
#include <stdint.h>

#include <lvgl.h>

#define HS_FONT_SIZE_COUNT 6
#define HS_FONT_WEIGHT_COUNT 2 /* regular, semibold */
#define HS_FONT_COUNT (HS_FONT_SIZE_COUNT * HS_FONT_WEIGHT_COUNT)

/* The px sizes, ascending — index is the size half of a font_id. */
extern const uint8_t hs_font_sizes[HS_FONT_SIZE_COUNT];

/**
 * Resolve a wire font_id to a font.
 *
 * font_id encodes size and weight: `size_index + (bold ? HS_FONT_SIZE_COUNT : 0)`.
 * Returns the nearest sane fallback rather than NULL for an out-of-range id, so a
 * malformed layout degrades to readable text instead of rendering nothing — the same
 * defensive posture as rasterizer.c clipping out-of-range coordinates.
 */
const lv_font_t *hs_font_get(uint8_t font_id);

/** Build a font_id from a size index and weight. */
static inline uint8_t hs_font_id(uint8_t size_index, bool bold)
{
	return (uint8_t)(size_index + (bold ? HS_FONT_SIZE_COUNT : 0));
}

#endif /* HS_FONTS_H_ */
