#include "hs_fonts.h"

/* Generated by tools/fonts/generate.mjs. Declared here rather than in a generated header
 * so the ladder's shape is visible in reviewable source: adding a size means editing
 * SIZES in the generator, this table, HS_FONT_SIZE_COUNT, and FONT_SIZES in
 * frontend/src/lib/layout.js — all four, deliberately, because they define one shared
 * contract. */
LV_FONT_DECLARE(lv_font_hs_regular_12)
LV_FONT_DECLARE(lv_font_hs_regular_16)
LV_FONT_DECLARE(lv_font_hs_regular_20)
LV_FONT_DECLARE(lv_font_hs_regular_24)
LV_FONT_DECLARE(lv_font_hs_regular_32)
LV_FONT_DECLARE(lv_font_hs_regular_48)
LV_FONT_DECLARE(lv_font_hs_semibold_12)
LV_FONT_DECLARE(lv_font_hs_semibold_16)
LV_FONT_DECLARE(lv_font_hs_semibold_20)
LV_FONT_DECLARE(lv_font_hs_semibold_24)
LV_FONT_DECLARE(lv_font_hs_semibold_32)
LV_FONT_DECLARE(lv_font_hs_semibold_48)

const uint8_t hs_font_sizes[HS_FONT_SIZE_COUNT] = {12, 16, 20, 24, 32, 48};

/* Order matters: index == font_id. Regular sizes ascending, then semibold ascending —
 * matching hs_font_id()'s arithmetic. */
static const lv_font_t *const hs_font_ladder[HS_FONT_COUNT] = {
	&lv_font_hs_regular_12,  &lv_font_hs_regular_16,  &lv_font_hs_regular_20,
	&lv_font_hs_regular_24,  &lv_font_hs_regular_32,  &lv_font_hs_regular_48,
	&lv_font_hs_semibold_12, &lv_font_hs_semibold_16, &lv_font_hs_semibold_20,
	&lv_font_hs_semibold_24, &lv_font_hs_semibold_32, &lv_font_hs_semibold_48,
};

/* Which font an unrecognized font_id falls back to: regular at the ladder's default
 * size, i.e. the same 16px the design editor starts a new element at
 * (frontend/src/lib/layout.js DEFAULT_FONT_SIZE). */
#define HS_FONT_FALLBACK_ID 1

const lv_font_t *hs_font_get(uint8_t font_id)
{
	if (font_id >= HS_FONT_COUNT) {
		return hs_font_ladder[HS_FONT_FALLBACK_ID];
	}
	return hs_font_ladder[font_id];
}
