/*
 * Host-native check that chunk_protocol.c produces byte-identical results to
 * gateway/gateway/protocol.py for the same inputs. Compiled with the system C compiler
 * against Zephyr header shims (tests/shims/) — this is the one piece of the firmware
 * that could actually be verified without the nRF Connect SDK toolchain or hardware,
 * so it's worth doing. See firmware/README.md for what's still unverified.
 *
 * Run: firmware/tests/run.sh
 */

#include <stdio.h>
#include <string.h>

#include "chunk_protocol.h"
#include "epaper.h"

static int failures = 0;

#define CHECK(cond, msg)                                                                         \
	do {                                                                                       \
		if (!(cond)) {                                                                    \
			printf("FAIL: %s (%s:%d)\n", msg, __FILE__, __LINE__);                   \
			failures++;                                                               \
		}                                                                                 \
	} while (0)

static size_t hex_to_bytes(const char *hex, uint8_t *out)
{
	size_t len = strlen(hex) / 2;
	for (size_t i = 0; i < len; i++) {
		sscanf(hex + 2 * i, "%2hhx", &out[i]);
	}
	return len;
}

/* Reference vectors generated by gateway/gateway/protocol.py — see the command in
 * firmware/tests/run.sh for how to regenerate these if the wire format ever changes. */
static const char *FULL_CHUNKS_HEX[] = {
	"0100000400b39f7856341268656c6c6f20776f726c642c",
	"0101000400b39f20746869732069732061207465737420",
	"0102000400b39f7061796c6f616420666f72206368756e",
	"0103000400b39f6b207265617373656d626c7921",
};
static const char *FULL_EXPECTED_DATA_HEX =
	"68656c6c6f20776f726c642c207468697320697320612074657374207061796c6f616420666f7220636"
	"8756e6b207265617373656d626c7921";
static const uint32_t FULL_EXPECTED_TARGET_HASH = 0x12345678;

static const char *DIFF_CHUNK_HEX = "0200000100a1d0bebafeca02010532312e35430503383825";
static const char *DIFF_EXPECTED_TLV_HEX = "02010532312e35430503383825";
static const uint32_t DIFF_EXPECTED_TARGET_HASH = 0xcafebabe;

static void test_full_message_multi_chunk(void)
{
	chunk_reassembler_t r;
	chunk_reassembler_reset(&r);

	uint8_t chunk_buf[64];
	uint8_t msg_type = 0;
	const uint8_t *payload = NULL;
	size_t payload_len = 0;
	bool complete = false;

	size_t n = sizeof(FULL_CHUNKS_HEX) / sizeof(FULL_CHUNKS_HEX[0]);
	for (size_t i = 0; i < n; i++) {
		size_t clen = hex_to_bytes(FULL_CHUNKS_HEX[i], chunk_buf);
		complete = chunk_reassembler_feed(&r, chunk_buf, clen, &msg_type, &payload,
						   &payload_len);
		if (i < n - 1) {
			CHECK(!complete, "should not be complete before the last chunk");
		}
	}
	CHECK(complete, "should be complete after the last chunk");
	CHECK(msg_type == CHUNK_MSG_TYPE_FULL, "msg_type should be FULL");

	uint32_t target_hash;
	const uint8_t *data;
	size_t data_len;
	bool unwrapped =
		chunk_protocol_unwrap_target_hash(payload, payload_len, &target_hash, &data, &data_len);
	CHECK(unwrapped, "unwrap should succeed");
	CHECK(target_hash == FULL_EXPECTED_TARGET_HASH, "target_hash should match Python vector");

	uint8_t expected_data[256];
	size_t expected_len = hex_to_bytes(FULL_EXPECTED_DATA_HEX, expected_data);
	CHECK(data_len == expected_len, "data_len should match Python vector");
	CHECK(memcmp(data, expected_data, expected_len) == 0, "data bytes should match Python vector");
}

static void test_diff_message_single_chunk(void)
{
	chunk_reassembler_t r;
	chunk_reassembler_reset(&r);

	uint8_t chunk_buf[64];
	size_t clen = hex_to_bytes(DIFF_CHUNK_HEX, chunk_buf);

	uint8_t msg_type = 0;
	const uint8_t *payload = NULL;
	size_t payload_len = 0;
	bool complete =
		chunk_reassembler_feed(&r, chunk_buf, clen, &msg_type, &payload, &payload_len);
	CHECK(complete, "single-chunk diff message should complete immediately");
	CHECK(msg_type == CHUNK_MSG_TYPE_DIFF, "msg_type should be DIFF");

	uint32_t target_hash;
	const uint8_t *data;
	size_t data_len;
	chunk_protocol_unwrap_target_hash(payload, payload_len, &target_hash, &data, &data_len);
	CHECK(target_hash == DIFF_EXPECTED_TARGET_HASH, "diff target_hash should match Python vector");

	uint8_t expected_tlv[64];
	size_t expected_len = hex_to_bytes(DIFF_EXPECTED_TLV_HEX, expected_tlv);
	CHECK(data_len == expected_len, "diff data_len should match Python vector");
	CHECK(memcmp(data, expected_tlv, expected_len) == 0, "diff TLV bytes should match Python vector");

	chunk_diff_entry_t entries[8];
	int count = chunk_protocol_decode_diff(data, data_len, entries, 8);
	CHECK(count == 2, "should decode 2 diff entries");
	CHECK(entries[0].element_id == 1, "entry 0 element_id should be 1");
	CHECK(entries[0].value_len == 5 && memcmp(entries[0].value, "21.5C", 5) == 0,
	      "entry 0 value should be '21.5C'");
	CHECK(entries[1].element_id == 5, "entry 1 element_id should be 5");
	CHECK(entries[1].value_len == 3 && memcmp(entries[1].value, "88%", 3) == 0,
	      "entry 1 value should be '88%%'");
}

static void test_corrupted_chunk_is_discarded(void)
{
	chunk_reassembler_t r;
	chunk_reassembler_reset(&r);

	uint8_t chunk_buf[64];
	size_t clen = hex_to_bytes(DIFF_CHUNK_HEX, chunk_buf);
	chunk_buf[clen - 1] ^= 0xFF; /* flip last payload byte -> CRC16 mismatch */

	uint8_t msg_type = 0;
	const uint8_t *payload = NULL;
	size_t payload_len = 0;
	bool complete =
		chunk_reassembler_feed(&r, chunk_buf, clen, &msg_type, &payload, &payload_len);
	CHECK(!complete, "corrupted single-chunk message must be discarded, not accepted");
}

static void test_out_of_order_chunk_is_discarded(void)
{
	chunk_reassembler_t r;
	chunk_reassembler_reset(&r);

	uint8_t chunk_buf[64];
	/* Feed chunk index 1 before index 0 — must be rejected (see chunk_protocol.h's
	 * note on requiring in-order delivery, unlike the Python side). */
	size_t clen = hex_to_bytes(FULL_CHUNKS_HEX[1], chunk_buf);
	uint8_t msg_type = 0;
	const uint8_t *payload = NULL;
	size_t payload_len = 0;
	bool complete =
		chunk_reassembler_feed(&r, chunk_buf, clen, &msg_type, &payload, &payload_len);
	CHECK(!complete, "starting mid-stream (index != 0) must not complete a message");
}

static void test_epaper_stub_applies_diff_bytes(void)
{
	/* Exercises the real epaper_apply_diff() against the same diff TLV bytes used
	 * above, end to end through chunk_protocol_decode_diff — the one part of
	 * epaper.c that isn't hardware-dependent. */
	uint8_t tlv[64];
	size_t len = hex_to_bytes(DIFF_EXPECTED_TLV_HEX, tlv);
	bool ok = epaper_apply_diff(tlv, len);
	CHECK(ok, "epaper_apply_diff should accept a well-formed diff TLV");

	uint8_t malformed[] = {0x05}; /* claims 5 entries, has none */
	CHECK(!epaper_apply_diff(malformed, sizeof(malformed)),
	      "epaper_apply_diff should reject malformed TLV data");
}

int main(void)
{
	test_full_message_multi_chunk();
	test_diff_message_single_chunk();
	test_corrupted_chunk_is_discarded();
	test_out_of_order_chunk_is_discarded();
	test_epaper_stub_applies_diff_bytes();

	if (failures == 0) {
		printf("All chunk_protocol native tests passed.\n");
		return 0;
	}
	printf("%d check(s) failed.\n", failures);
	return 1;
}
